services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile

  test:
    image: test
    build:
      context: .
      dockerfile: test/Dockerfile
