name: .NET Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dotnet-version: ['8.0.x']
        
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ matrix.dotnet-version }}
            
      - name: Install dependencies
        run: dotnet restore taf_server.sln
      
      - name: Build
        run: dotnet build --configuration Release taf_server.sln
        
      - name: Test with dotnet CLI
        run: dotnet test --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}" taf_server.sln

      - name: Publish
        run: |
          mkdir -p ./artifacts/publish
          dotnet publish taf_server.sln -c Release -o ./artifacts/publish
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: presentations-artifacts
          path: ./artifacts/publish
        if: ${{ always() }}
        
#      - name: Upload dotnet test results
#        uses: actions/upload-artifact@v4
#        with:
#          name: dotnet-results-${{ matrix.dotnet-version }}
#          path: TestResults-${{ matrix.dotnet-version }}
#        if: ${{ always() }}
        