name: .NET Build
on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
          #        service:
          #          - name: identity_server
          #            project: src/IdentityServer/IdentityServer.csproj
          #          - name: presentations
          #            project: src/Presentations/Presentations.csproj
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Install dependencies
        run: dotnet restore taf_server.sln

      - name: Build
        run: dotnet build taf_server.sln --configuration Release --verbosity minimal --no-restore

      - name: Test with dotnet CLI
        run: dotnet test taf_server.sln --configuration Release --verbosity minimal --no-build --no-restore --logger trx --results-directory "TestResults"

      - name: Publish
        run: dotnet publish taf_server.sln --configuration Release --no-build --no-restore -o "./publish"
          
          #      - name: Publish ${{ matrix.service.name }}
          #        run: |
          #          mkdir -p ./artifacts/${{ matrix.service.name }}
          #          dotnet publish "${{ matrix.service.project }}" -c Release -o "./artifacts/${{ matrix.service.name }}"

      - name: Upload core artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./publish/**/*
          compression-level: 9
        if: success()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults
        if: always()
        
        #      - name: Upload ${{ matrix.service.name }} artifacts
        #        uses: actions/upload-artifact@v4
        #        with:
        #          name: ${{ matrix.service.name }}-artifacts
        #          path: ./artifacts/${{ matrix.service.name }}
        #        if: ${{ always() }}
        
        #      - name: Upload dotnet test results
        #        uses: actions/upload-artifact@v4
        #        with:
        #          name: dotnet-results-${{ matrix.dotnet-version }}
        #          path: TestResults-${{ matrix.dotnet-version }}
        #        if: ${{ always() }}
        